spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: ${POSTGRES_USER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create # ou validate, dependendo da sua necessidade
    show-sql: true
